# Generated by Django 3.1 on 2020-08-10 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bildungsspre_chApplikation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='related',
            field=models.ManyToManyField(related_name='_word_related_+', to='Bildungsspre_chApplikation.Word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
