# Generated by Django 3.1 on 2020-08-10 13:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bildungsspre_chApplikation', '0002_auto_20200810_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='name',
            new_name='word',
        ),
        migrations.RemoveField(
            model_name='field',
            name='description',
        ),
        migrations.RemoveField(
            model_name='field',
            name='word',
        ),
        migrations.AddField(
            model_name='field',
            name='related',
            field=models.ManyToManyField(related_name='_field_related_+', to='Bildungsspre_chApplikation.Field'),
        ),
        migrations.AddField(
            model_name='field',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(default='Wissenschaftlich', on_delete=django.db.models.deletion.SET_DEFAULT, to='Bildungsspre_chApplikation.field')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bildungsspre_chApplikation.word')),
            ],
        ),
    ]
