# Generated by Django 3.1 on 2020-08-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bildungsspre_chApplikation', '0003_auto_20200810_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['word']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='description',
            order_with_respect_to='word',
        ),
    ]
