# Generated by Django 3.1 on 2020-08-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bildungsspre_chApplikation', '0006_auto_20200810_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='related',
        ),
        migrations.AddField(
            model_name='field',
            name='related_fields',
            field=models.ManyToManyField(blank=True, related_name='_field_related_fields_+', to='Bildungsspre_chApplikation.Field'),
        ),
    ]
