# Generated by Django 3.1 on 2020-08-10 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bildungsspre_chApplikation', '0008_auto_20200810_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['word'], 'verbose_name': 'word', 'verbose_name_plural': 'words'},
        ),
        migrations.AddField(
            model_name='word',
            name='wortart',
            field=models.CharField(choices=[('ADJ', 'Adjective'), ('ADV', 'Adverb'), ('VER', 'Verb'), ('SUB', 'Substantiv, Nomen')], default='SUB', max_length=3),
        ),
        migrations.AlterField(
            model_name='description',
            name='field',
            field=models.ForeignKey(default='Bildungssprachlich', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='related_field', to='Bildungsspre_chApplikation.field'),
        ),
        migrations.AlterField(
            model_name='description',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_descriptions', to='Bildungsspre_chApplikation.word'),
        ),
    ]
