# Generated by Django 3.1 on 2020-09-12 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bildungsspre_chApplikation', '0012_auto_20200813_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='word_type',
            field=models.CharField(blank=True, choices=[('ADJ', 'Adjektiv'), ('ADV', 'Adverb'), ('INT', 'Interjektion'),
                                                        ('KON', 'Konjunktion'), ('PRÄ', 'Präposition'),
                                                        ('PRO', 'Pronomen'), ('SUB', 'Substantiv, Nomen'),
                                                        ('VER', 'Verb')], default='SUB', max_length=3),
        ),
    ]
