# Generated by Django 3.1 on 2020-09-12 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bildungsspre_chApplikation', '0013_auto_20200912_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=models.SET(1), to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=models.SET(1), to=settings.AUTH_USER_MODEL),
        ),
    ]
